name: Update README
# 1. トリガーとして`cron`を使う
on:
  schedule:
    - cron: '37 * * * *' # 1時間ごとに実行
  # 2. テストやデバッグしやすいように手動で実行できるよう`workflow_dispatch`もつけておく
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update zenn rss feed
        # 3. シェルスクリプトをactions内で実行できるよう、`chmod`で実行権限を付与する
        # 4. シェルスクリプトへのパスを`${GITHUB_WORKSPACE}`を使って表現する（使わなくてもOKだと思う）
        run: |
          chmod +x "${GITHUB_WORKSPACE}/rss-feed.sh"
          "${GITHUB_WORKSPACE}/rss-feed.sh"
      - name: git commit
          # 5. スクリプト実行後に`README.md`を直前のコミットと比較して差分があればコミットしてプッシュ
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "haoblackj"
          git add README.md
          git diff --cached --quiet || git commit -m "Update Zenn RSS feed"; git push origin main